"""empty message

Revision ID: 019cd21d88ef
Revises: 8e65b9b6bd92
Create Date: 2026-04-04 22:35:08.296104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019cd21d88ef'
down_revision = '8e65b9b6bd92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_slot_per_service_staff_time', ['tenant_id', 'staff_id', 'service_id', 'time'])

    with op.batch_alter_table('business_users', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_business', ['user_id', 'business_id'])
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint('unique_user_business', type_='unique')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint('unique_slot_per_service_staff_time', type_='unique')

    # ### end Alembic commands ###
