"""empty message

Revision ID: 3884785ba7b5
Revises: b663e015306a
Create Date: 2026-03-18 09:19:21.132624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3884785ba7b5'
down_revision = 'b663e015306a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email'),
    sa.UniqueConstraint('tenant_id', 'staff_id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_service_per_business', ['tenant_id', 'master_service_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint('unique_service_per_business', type_='unique')

    op.drop_table('staff')
    # ### end Alembic commands ###
