"""remove business image

Revision ID: 7daa29f34ae4
Revises: f1f36ff5878d
Create Date: 2026-03-04 17:59:03.103826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7daa29f34ae4'
down_revision = 'f1f36ff5878d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_filename', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('business_images_business_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('business_images_pkey'))
    )
    # ### end Alembic commands ###
