"""empty message

Revision ID: b663e015306a
Revises: 7daa29f34ae4
Create Date: 2026-03-10 17:24:55.904208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b663e015306a'
down_revision = '7daa29f34ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('master_service_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('services_business_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'businesses', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'master_services', ['master_service_id'], ['id'])
        batch_op.drop_column('business_id')
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('services_business_id_fkey'), 'businesses', ['business_id'], ['id'])
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.drop_column('duration')
        batch_op.drop_column('master_service_id')
        batch_op.drop_column('tenant_id')

    op.drop_table('master_services')
    # ### end Alembic commands ###
