"""empty message

Revision ID: c5d90024f374
Revises: d6433699027f
Create Date: 2026-03-21 11:38:36.550081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d90024f374'
down_revision = 'd6433699027f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Explicitly cast 'time' column from VARCHAR to TIMESTAMP
    op.execute('ALTER TABLE appointment ALTER COLUMN time TYPE TIMESTAMP USING time::timestamp')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        # service_id and tenant_id adjustments
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'businesses', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # Explicitly cast 'time' column back to VARCHAR
    op.execute('ALTER TABLE appointment ALTER COLUMN time TYPE VARCHAR(50) USING time::varchar')

    # ### end Alembic commands ###